name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test-and-push:
    runs-on: ubuntu-latest
    # 授予工作流写入GitHub Packages的权限
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- 测试部分 (和之前一样) ---
      - name: Set up Python and test backend
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install backend dependencies and run tests
        run: |
          pip install -r backend/requirements.txt
          flask --app backend/app.py --version

      - name: Set up Node.js and test frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend dependencies and run build
        run: |
          npm --prefix ./frontend install
          npm --prefix ./frontend run build

      # --- 新增：登录到GitHub Container Registry ---
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 新增：构建并推送后端镜像 ---
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      # --- 新增：构建并推送前端镜像 ---
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest